service: MySererlessProjectForTCTWO

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::my-imp-data-bucket/*

plugins:
  - serverless-python-requirements 
  
custom:
  FILES_BUCKET: my-imp-data-bucket 
  
package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!requirements.txt"
    - "!package.json"

 
functions:
  getjson: ${file(./Resources/getjson.yml)}  
  getdata: ${file(./Resources/getdata.yml)}  